variables:
  OUTPUT_NAME: "app"

stages:
  # - build
  - deploy

build_go_app:
  image: golang:latest
  stage: build
  script:
    - cd go_app
    - go mod download
    - go build -o $OUTPUT_NAME ./cmd
  artifacts:
    paths:
      - "go_app/$OUTPUT_NAME"
    expire_in: 1 week

deploy:
  image: docker:latest
  stage: deploy
  before_script:
    - apk add --quiet python3 curl
    - curl -s -o jq.py -0 https://git.forestier.re/uca/2022-2023/devops-m1/jq/-/raw/main/jq.py
    - . ./init.sh
    - echo $USERNAME $PASSWORD
    - docker login docker-registry.edu.forestier.re -u $USERNAME -p $PASSWORD
  script:
    - cd go_app
    - docker build -t docker-registry.edu.forestier.re/elleriche/$OUTPUT_NAME .
