stages:
  - build
  - deploy

build:
  image: golang
  stage: build
  script:
    - go mod download
    - go build -o ./app ./go_app/cmd
  artifacts:
    paths:
      - build/libs/app
    expire_in: 1 week
deploy:
  image: debian:bullseye
  stage: deploy
  script:
    - ls -lsa build/libs/app
  when: manual
