variables:
  OUTPUT_NAME: "app"

stages:
  - build
  - deploy

build:
  image: golang:latest
  stage: build
  script:
    - cd go_app
    - go mod download
    - go build -o $OUTPUT_NAME ./cmd
  artifacts:
    paths:
      - $OUTPUT_NAME
    expire_in: 1 week
deploy:
  image: debian:bullseye
  stage: deploy
  script:
    - ls -lsa build/libs/app
  when: manual
