## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service" }}.{{ index .Labels "com.docker.compose.project" }}.local`)'

# API and dashboard configuration
api:
  insecure: true
