docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_images:
  - "mariadb:latest"
  - "traefik:latest"
  - "nextcloud:latest"
  - "wordpress:latest"
  - "grafana/grafana:latest"
  - "quay.io/prometheus/node-exporter:latest"

mariadb_root_password: "root"

openstack_dir: "/dev/vdb"
mount_dir: "/mnt/volume"
volume_names:
  - "MariaDB"
  - "Nextcloud"
  - "Wordpress"

mariadb_names:
  - "alpha"
  - "beta"

domain_name: "eliaz.uca-devops.ovh"

docker_network: "maria-net"
