docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_images:
  - "mariadb:latest"
  - "nextcloud:latest"
  - "wordpress:latest"

mariadb_root_password: "root"

openstack_dir: "/dev/vdb"
mount_dir: "/mnt/volume"
volume_name: "volume"

mariadb_names:
  - "alpha"
  - "beta"
