- name: login to the docker registry
  ansible.builtin.docker_login:
    registry: docker-registry.edu.forestier.re
    username: "{{ docker_user }}"
    password: "{{ docker_password }}"
  become: true
  tags: docker

- name: Pull the Go app container image from the registry and start the container
  ansible.builtin.docker_container:
    name: go_app
    image: docker-registry.edu.forestier.re/elleriche/app:latest
    state: present
    restart_policy: always
    labels: traefik.enable="true"
      traefik.http.routers.go_app.rule="Host(`go_app.eliaz.uca-devops.ovh`)"
      traefik.http.routers.go_app.entrypoints="secure"
      traefik.http.services.go_app.loadbalancer.server.port=80
      traefik.http.routers.go_app.tls=true
      traefik.http.routers.go_app.tls.certresolver="letsencrypt"
  become: true
  tags: go_app
