- name: Deploy the MariaDB container
  ansible.builtin.docker_container:
    name: mariadb
    image: mariadb:latest
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
    ports:
      - "3306:3306"
    volumes:
      - "/{{ volume_names[0] }}:/var/lib/mysql"
    state: started
    restart_policy: always
  become: true

- name: install pip3
  ansible.builtin.package:
    name: python3-pip
    state: present
  become: true

- name: Make sure pymysql is present
  ansible.builtin.pip:
    name: pymysql
    state: present
  become: true

- name: Add a database to the MariaDB container
  ansible.builtin.mysql_db:
    name: "{{ item }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ mariadb_names }}"

- name: Add a user to the MariaDB container
  ansible.builtin.mysql_user:
    name: "{{ item }}"
    password: ""
    priv: "*.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ mariadb_names }}"
