- name: Start the Nextcloud container
  ansible.builtin.docker_container:
    name: nextcloud
    image: nextcloud
    volumes:
      - "/{{ volume_names[1] }}:/var/www/html"
    env:
      MYSQL_HOST: MariaDB
      MYSQL_DATABASE: "{{ mariadb_names[0] }}"
      MYSQL_USER: "{{ mariadb_names[0] }}"
      MYSQL_PASSWORD: ""
    restart_policy: always
    state: started
    labels: traefik.enable="true"
      traefik.http.routers.nextcloud.rule="Host(`nextcloud.{{ domain_name }}`)"
      traefik.http.routers.nextcloud.entrypoints="secure"
      traefik.http.services.nextcloud.loadbalancer.server.port=80
      traefik.http.routers.nextcloud.tls=true
      traefik.http.routers.nextcloud.tls.certresolver="letsencrypt"

  become: true
  tags: nextcloud
