- name: Web app deployment
  hosts: servers
  become: false
  any_errors_fatal: true
  vars_files:
    - "{{ playbook_dir }}/vars/vars_app.yml"
  tasks:
    - name: set nameservers
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"

    - name: create list in a variable with the names of the packages
      ansible.builtin.set_fact:
        packages:
          - apache2
          - firewalld

    - name: install packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: boot services
      become: true
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ app_services }}"

    - name: open port 80
      become: true
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: health check
      uri:
        url: "http://localhost/"
        return_content: true
      register: result
      until: result.status == 200
      retries: 12
      delay: 5
