- name: Copy the traefik configuration file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/traefik.yml"
    dest: "./traefik.yml"
  become: true

- name: Start the traefik container
  ansible.builtin.docker_container:
    name: traefik
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: --providers.docker
    restart_policy: always
    state: started
  become: true

- name: Copy the traefik acme file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/acme.json"
    dest: "./traefik/acme.json"
  become: true
