- name: Start the Wordpress container
  ansible.builtin.docker_container:
    name: wordpress
    image: wordpress:latest
    volumes:
      - "/{{ volume_names[2] }}:/var/www/html"
    env:
      WORDPRESS_DB_HOST: MariaDB
      WORDPRESS_DB_NAME: "{{ mariadb_names[1] }}"
      WORDPRESS_DB_USER: "{{ mariadb_names[1] }}"
      WORDPRESS_DB_PASSWORD: ""
    restart_policy: always
    state: started
    labels: traefik.enable="true"
      traefik.http.routers.wordpress.rule="Host(`wordpress.{{ domain_name }}`)"
      traefik.http.routers.wordpress.entrypoints="secure"
      traefik.http.services.wordpress.loadbalancer.server.port=80
      traefik.http.routers.wordpress.tls=true
      traefik.http.routers.wordpress.tls.certresolver="letsencrypt"
  become: true
  tags: wordpress
